# Generated by Django 3.1.6 on 2021-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Team', models.CharField(max_length=100)),
                ('Active', models.BooleanField()),
            ],
        ),
    ]
